spring:
  data:
    mongodb:
      database: travelagency
      username: travelagency

server:
  port: 8002
  
logging:
  level:
    org.springframework.web: DEBUG
    com.peterjurkovic.travelagency: DEBUG

nexmo:
  jwtPrivateKey: /home/nicolagiacchetta/personal/travel-agency/keys/private.key

conversation:
  url: http://localhost:8002
  number:
    UK: 447520632858
    SW: 46765196078

database:
  populateData : true

