
server:
  port: 80
  

thymeleaf:
    cache: true
    
client:
  security:
    twoFaEnabled: true 
   
logging:
  level:
    org.springframework.web: INFO
    com.peterjurkovic.travelagency: DEBUG
    com.nexmo.client.voice : TRACE
  file: client.log
  pattern:
    console: 

voice:
  answerUrl: http://travelwise.fun/static/ncco.json
  
conversation:
  url: http://travelwise.fun:8002

database:
  populateData : false