spring:
  data:
    mongodb:
      database: travelagency
      username: travelagency

  thymeleaf:
    cache: false
    
server:
  port: 8001
  
company:
  name: TravelWise  
  
client:
  security:
    twoFaEnabled: false 

voice:
  answerUrl: http://www.nicolagiacchetta.it/travel/ncco.json