spring:
  data:
    mongodb:
      database: travelagency
      username: travelagency

  thymeleaf:
    cache: false
    
server:
  port: 8001
  
company:
  name: TravelWise  
  
client:
  security:
    twoFaEnabled: false 

voice:
  answerUrl: http://www.nicolagiacchetta.it/travel/ncco.json
  agentNumber: 447397921621

nexmo:
  apiKey: abecb1a7
  apiSecret: 4965c0e6df2a0db9
  applicationId: 094555bc-747e-4c60-bbe9-b37892a2818f
  jwtPrivateKey: /home/nicolagiacchetta/personal/travel-agency/keys/private.key

